[tool.black]
line-length = 88
target-version = ['py312']

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "C", "B"]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
"pipeline/ui.py" = ["C901", "S110", "S602"]

[tool.isort]
profile = "black"
line_length = 88
