name: Deploy Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  pages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

  smoke-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Pages to become available
        run: |
          set -e
          URL="https://rogerjs93.github.io/datapipeline/"
          echo "Checking $URL"
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo 000)
            echo "Attempt $i -> HTTP $STATUS"
            if [ "$STATUS" = "200" ]; then
              echo "Pages site is live"
              exit 0
            fi
            sleep 6
          done
          echo "Pages did not become available"; exit 1
