name: Upload Artifacts to S3

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip awscli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync artifacts to S3
        # Upload artifacts to the workflow run so they can be inspected even if S3 is not configured
      - name: Upload pipeline artifacts to workflow
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: pipeline/artifacts

      - name: Sync artifacts to S3
        if: ${{ secrets.S3_BUCKET != '' }}
        run: |
          set -e
          PREFIX="${{ secrets.S3_PREFIX }}"
          if [ -z "$PREFIX" ]; then
            aws s3 sync pipeline/artifacts s3://${{ secrets.S3_BUCKET }} --delete
          else
            aws s3 sync pipeline/artifacts s3://${{ secrets.S3_BUCKET }}/$PREFIX --delete
          fi
